---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: farmanahmed
  become: false
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "spe_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
      when: ansible_facts['os_family'] == "Debian"

    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name spe_calculator spe_calculator
